version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - stevenkuhn
  ignore:
  - dependency-name: InRule.Authoring.Core
    versions:
    - "> 5.2.0"
  - dependency-name: InRule.Authoring.SDK
    versions:
    - "> 5.2.0"
  - dependency-name: InRule.Common
    versions:
    - "> 5.2.0"
  - dependency-name: InRule.Repository
    versions:
    - "> 5.2.0"
  - dependency-name: InRule.Runtime
    versions:
    - "> 5.2.0"
  - dependency-name: Microsoft.AspNet.WebApi.Client
    versions:
    - "> 5.2.3"
  - dependency-name: Newtonsoft.Json
    versions:
    - "> 10.0.3"
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: LibGit2Sharp
    versions:
    - 0.27.0-preview-0096
