name: $(GitVersion_FullSemVer)
pool: Default

steps:
- task: GitVersion@4
  displayName: Calculate GitVersion

- task: Cake@0
  displayName: Run Cake build script
  inputs:
    script: 'build.cake'
    target: 'CI'
    verbosity: 'Verbose'
    arguments: '-configuration Release -ScriptArgs '''''

- task: PublishTestResults@2
  displayName: Publish Test Results [netcoreapp2.2]
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/netcoreapp2.2/TestResult_*.trx'
    testRunTitle: netcoreapp2.2
    mergeTestResults: true
    failTaskOnFailedTests: true

- task: PublishTestResults@2
  displayName: Publish Test Results [net461]
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/net461/TestResult_*.trx'
    testRunTitle: net461
    mergeTestResults: true
    failTaskOnFailedTests: true