name: $(GitVersion_FullSemVer)
pool: Default

trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - v*

pr:
  branches:
    include:
    - '*'

variables:
  buildTarget: CI

steps:
- script: |
    echo '##vso[task.setvariable variable=buildTarget]Release'
  displayName: Setting build target if triggered by tag
  condition: startsWith($(Build.SourceBranch), 'refs/tags/')

- task: GitVersion@4
  displayName: Calculate GitVersion

- task: Cake@0
  displayName: Run Cake build script
  inputs:
    script: 'build.cake'
    target: $(buildTarget)
    verbosity: 'Verbose'
    arguments: '-configuration="Release"'
    env:
      GitHub_Access_Token: $(gitHubAccessToken)
      NuGet_Publish_Source: $(mygetApiKey)

- task: PublishTestResults@2
  displayName: Publish Test Results [netcoreapp2.2]
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/netcoreapp2.2/TestResult*.trx'
    testRunTitle: netcoreapp2.2
    mergeTestResults: true
    failTaskOnFailedTests: true

- task: PublishTestResults@2
  displayName: Publish Test Results [net461]
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/net461/TestResult*.trx'
    testRunTitle: net461
    mergeTestResults: true
    failTaskOnFailedTests: true