name: $(GitVersion_FullSemVer)
pool: Default

steps:
- task: GitVersion@4
  displayName: Calculate GitVersion

- task: Cake@0
  displayName: Run Cake build script
  inputs:
    script: 'build.cake'
    target: 'Default'
    verbosity: 'Verbose'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/TestResult_*.trx'
    mergeTestResults: false
    failTaskOnFailedTests: true