name: $(GitVersion_FullSemVer)
pool: Default

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - v*

pr:
  branches:
    include:
    - '*'

variables:
  buildTarget: CI

jobs:

- job: BuildAndTest
  displayName: Build and Test
  strategy:
    matrix: 
      for_InRule_v520:
        InRule_Version: '5.2.0'
      for_InRule_v530:
        InRule_Version: '5.3.0'
      for_InRule_v531:
        InRule_Version: '5.3.1'
      for_InRule_v540:
        InRule_Version: '5.4.0'
      for_InRule_v541:
        InRule_Version: '5.4.1'
      for_InRule_v542:
        InRule_Version: '5.4.2'
      for_InRule_v543:
        InRule_Version: '5.4.3'
      for_InRule_v550:
        InRule_Version: '5.5.0'
    maxParallel: 5
  workspace: 
    clean: all  
  
  steps:

  #- script: "echo ##vso[task.setvariable variable=buildTarget]Release"
  #  displayName: Setting build target if triggered by tag
  #  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

  - task: GitVersion@5
    displayName: Calculate GitVersion
    inputs:
      runtime: 'core'

  - task: Cake@0
    displayName: Run Cake build script
    inputs:
      script: 'build.cake'
      target: $(buildTarget)
      verbosity: 'Verbose'
      arguments: '-configuration="Release"'
    env:
      GitHub_Access_Token: $(gitHubAccessToken)
      NuGet_ApiKey: $(nugetApiKey)

  - task: PublishTestResults@2
    displayName: Publish Test Results [netcoreapp3.1]
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/netcoreapp3.1/TestResult*.trx'
      testRunTitle: netcoreapp3.1
      mergeTestResults: true
      failTaskOnFailedTests: true

  - task: PublishTestResults@2
    displayName: Publish Test Results [net461]
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/net461/TestResult*.trx'
      testRunTitle: net461
      mergeTestResults: true
      failTaskOnFailedTests: true