name: $(GitVersion_FullSemVer)
pool: Default

steps:
- task: GitVersion@4
  displayName: Calculate GitVersion

- task: Cake@0
  displayName: Run Cake build script
  inputs:
    script: 'build.cake'
    target: 'Default'
    verbosity: 'Verbose'