name: Build

on: [push, pull_request]

jobs: 
  build_windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.101'

    - name: Setup Cake
      run: dotnet tool restore
      
    - name: Run Cake
      run: dotnet cake --target="GitHub"
    
