name: Build

on: [push, pull_request]

jobs: 
  build_windows:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        inrule: [5.2.0, 5.5.0]

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.101'

    - name: Restore .NET Core Tools
      run: dotnet tool restore

    - name: Run Cake
      env:
        InRule_Version: ${{ matrix.inrule }}
      run: dotnet cake --target="GitHub"
    
