name: Build

on: [push]

jobs: 
  build_windows:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        inrule: [5.2.0, 5.4.3, 5.5.0]

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - uses: actions/checkout@master

    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.101'

    - name: Restore .NET Core Tools
      run: dotnet tool restore

    - name: Run Cake
      env:
        InRule_Version: ${{ matrix.inrule }}
      run: dotnet cake --target="GitHub"
    
