name: Build

on: [push]

jobs: 
  build:
    name: Build
    runs-on: [ self-hosted, windows, ubuntu-latest ]

    strategy:
      matrix:
        inrule: [5.2.0, 5.3.1, 5.4.3, 5.5.1]

    steps:
    - name: Checkout Source
      uses: actions/checkout@master

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Restore .NET Core Tools
      run: dotnet tool restore

    - name: Run Cake
      env:
        InRule_Version: ${{ matrix.inrule }}
      run: |
        dotnet cake --bootstrap
        dotnet cake --target="CI"

#  release:
#    name: Create release
#    runs-on: ubuntu-latest
#    needs: [ build ]
#
#    if: startsWith( github.ref, 'refs/tags/v' )
#    steps:
#    - name: 
    
