name: Build

on: [push]

jobs: 
  build_windows:
    name: Build [windows]
    runs-on: [self-hosted, windows]

    strategy:
      matrix:
        inrule: [5.2.0, 5.3.1, 5.4.3, 5.5.1]

    steps:
    - name: Checkout Source
      uses: actions/checkout@master

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Restore .NET Core Tools
      run: dotnet tool restore

    - name: Run Cake
      env:
        InRule_Version: ${{ matrix.inrule }}
      run: |
        dotnet cake --bootstrap
        dotnet cake --target="Publish-Artifacts"

    - name: Upload artifacts
      if: matrix.inrule == '5.2.0'
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts
  
  build_ubuntu:
    name: Build [ubuntu]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        inrule: [5.2.0, 5.3.1, 5.4.3, 5.5.1]

    steps:
    - name: Checkout Source
      uses: actions/checkout@master

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Restore .NET Core Tools
      run: dotnet tool restore

    - name: Run Cake
      env:
        InRule_Version: ${{ matrix.inrule }}
      run: |
        dotnet cake --bootstrap
        dotnet cake --target="Publish-Artifacts"

#  release:
#    name: Create release
#    runs-on: ubuntu-latest
#    needs: [ build_ubuntu, build_windows ]

#    if: startsWith( github.ref, 'refs/tags/v' )
#    steps:
  
    
